### ISSUE TITLE
Layer dynamic shape

### ISSUE THREAD

**Issue by andreyvolokitin** [ygalanter/pebble-effect-layer#1]
How hard would it be to make a layer with a vector shape and to change this shape dynamically while applying effect?

**Comment by ygalanter** [comment]
well you can use try playing around with [GPath ](https://developer.pebble.com/docs/c/Graphics/Drawing_Paths/)

**Comment by andreyvolokitin** [comment]
I mean the effect layer itself, it is rectangular by definition, so the boundaries of the effect are rectangular. But it looks like every layer is rectangular in pebble API so we probably can't create non-rectangular layers...

**Comment by ygalanter** [comment]
Have you seen the Mask effect? You can apply a mask (in form of primitive shape or an image) and then combine it with other effects. E.g https://twitter.com/YGalanter/status/587049089981882370?s=19

**Comment by andreyvolokitin** [comment]
Yeah, I considered it and will look into it more closely, didn't realize it can be combined with other effects. Another question: is there any other way to rotate a mask with another combined effect other than calculating a new mask shape with a new angle, clearing old mask and then reapplying the new mask with the effect (if it is even viable)?

**Comment by ygalanter** [comment]
Yes effects can be [combined](https://www.instagram.com/p/445atyuwVA/?tagged=yg_pebble)
Regarding rotating mask - you should be able to create a mask out of GPath and GPath has built in rotation routines.

**Comment by andreyvolokitin** [comment]
Thanks!

**Comment by andreyvolokitin** [comment]
> you should be able to create a mask out of GPath and GPath has built in rotation routines

Looks like `EffectMask` is [expecting GBitmap](https://github.com/ygalanter/pebble-effect-layer/blob/master/src/c/effects.c#L623) for the `bitmap_mask` property, and `GPath` has its own method to draw itself. So I need to convert `GPath` to bitmap, then assign that bitmap to the `EffectMask->bitmap_mask`? Probably not, because that way I probably can't use rotation routines for GPath... Or am I missing something?

**Comment by andreyvolokitin** [comment]
Or you meant that I need to create new mask from the bitmap of rotated `GPath` on each angle change?

**Comment by andreyvolokitin** [comment]
Hmm, seems like I need to implement new `effect_mask` which will support masking/drawing `GPath` along with drawing text and bitmap...

**Comment by andreyvolokitin** [comment]
Also, I'm not quite sure how exactly I can actually limit the shape of application area of some effect with the mask. Judging by code, the mask effect exchanges mask pixels to corresponding pixels from the provided bitmap (`bitmap_background `). While what I need is to change frame buffer (onscreen) pixels which are intersecting with/bounded by the mask, to the pixels which are produced by applying some other effect to the same screen region (`colorize` effect in my case). That is what I initially called "effect layer with dynamic shape"
